---
driver:
  name: vagrant

platforms:
  - name: ubuntu-14.04
  # - name: debian-8.2
  - name: centos-7.2
  - name: centos-6.8
  # - name: centos-5.11

suites:
  - name: yum-default
    run_list:
      - recipe[yum]
      - recipe[clamav]
    includes:
    - centos-7.2
    - centos-6.8
  - name: yum-enabled
    run_list:
    - recipe[yum]
    - recipe[clamav]
    attributes:
      clamav:
        clamd:
          enabled: true
        freshclam:
          enabled: true
    includes:
    - centos-7.2
    - centos-6.8
  - name: apt-default
    run_list:
      - recipe[apt]
      - recipe[clamav]
    includes:
    - ubuntu-14.04
  - name: apt-enabled
    run_list:
    - recipe[apt]
    - recipe[clamav]
    attributes:
      clamav:
        clamd:
          enabled: true
           # match default apparmor config
          LocalSocket: /run/clamav/clamd.ctl
        freshclam:
          enabled: true
    includes:
    - ubuntu-14.04
